export const SEARCH_PARAMS = {
  PAGE_SIZE: 'pageSize',
  PAGE_INDEX: 'pageIndex',
  KEYWORD: 'keyword',
  DATE: 'date',
  DAY: 'day',
  FROM_DATE: 'fromDate',
  TO_DATE: 'toDate',
  DOCTOR_ID: 'doctorId',
  DEPARTMENT: 'departmentCodes',
  POSITION: 'positionCodes',
  LEAVE_TYPE: 'leaveType',
  MODE: 'mode',
  YEAR: 'year',
  MONTH: 'month',
  DIALOG: 'dialog',
  ID: 'id',
  VIEW: 'view',
  CATEGORY_CODE: 'categoryCode',
  USER: 'user',
  STATUS: 'status',
  NAME: 'name',
  EMPLOYEE_CODE: 'employeeCode',
  VALUE: 'value',
  CODE: 'code',
  TYPE: 'type',
  ROLE_ID: 'roleId',
  ROLE: 'role',
  AUTHOR_ID: 'authorId',
  DEPARTMENTS: 'departmentCodes',
  CATEGORY: 'category',

  AIRLINE: 'airline',
  ROUTING_GROUP: 'routingGroup',
  TYPE_CODE: 'typeCode',
  MATERIAL_CATALOG_ID: 'materialCatalogId',
  CATEGORY_ID: 'categoryId',
  AIRLINE_CODE: 'airlineCode',
  CLONE_ID: 'cloneId',
  EMPLOYEE_ID: 'employeeId',
  PERS_CODE: 'persCode',
};

export const SEARCH_PARAM_VALUES = {
  MODIFY: 'modify',
  HISTORY: 'history',
  APPROVAL: 'approval',
  MODIFY_DEPARTMENT: 'modifyDepartment',
  MODIFY_HOLIDAY: 'modifyHoliday',
  ADD_EMPLOYEES_FOR_DEPARTMENT: 'addEmployeesForDepartment',
  ADD_EMPLOYEES_FOR_CREW: 'addEmployeesForCrew',
  ADD_CREW: 'addCrew',
  SCHEDULE: 'schedule',
  COPY: 'copy',
  DETAIL: 'detail',
  MODIFY_DETAIL: 'modifyDetail',
  MODIFY_EMPLOYEE_ROLE: 'modifyEmployeeRole',
};
